# Generated by Django 5.0.7 on 2024-07-30 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='firstname',
            new_name='name',
        ),
    ]
